"""add phone number columns

Revision ID: 50605ed94ebd
Revises: 873340cf74f3
Create Date: 2025-09-23 13:30:08.269454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50605ed94ebd'
down_revision = '873340cf74f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classteachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('classteachers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
